### ISSUE TITLE
Point real in polygon edge, but within_map return False

### ISSUE THREAD

**Issue by PonyPC** [MrMinimal64/extremitypathfinder#11]
version: 1.2.0

boundary: [(-3573.063493809924, -3397.7041999887488), (1301.0459112892288, -252.2710863523747), (1301.15422849654, -252.28188515495947), (4770.1483895222245, -3628.3511913003213), (2834.943959525434, 3975.1684750915865), (-1867.1813387156046, 2849.7191787712245)]
holes: [[(2060.962499654814, 2402.856442923204), (2061.0991856380538, 2402.7975366689266), (2505.6489788642275, 1262.568360564638), (2505.4964894782643, 1262.374772157754), (67.8754446874187, 1594.3012258568667), (67.82916999672895, 1594.6696523014614)]]
starting to ending point: (2436.2142928243047, 1440.6619196276174)
(2505.6489788642275, 1262.568360564638)

ValueError: start or goal do not lie within the map
environment.within_map(starting point) -> False
environment.within_map(ending point) -> True

So how to deal with precision?

**Comment by PonyPC** [comment]
Temporary solution:

class MyPolygonEnvironment(PolygonEnvironment):
	def within_map(self, coords):
		return True
environment = MyPolygonEnvironment()

**Comment by MrMinimal64** [comment]
could you please post a minimal example and state which edge causes the problem? I guess for these kind of very close cases it is very hard to distinguish "inside" from "outside" and it hence is best to skip the "within_map" test, as you did. in the newest version v1.3.0 I added the option ``verify`` to ``find_shortest_path()`` for skipping the 'within map' test for goal and start points.

**Comment by PonyPC** [comment]
from extremitypathfinder import PolygonEnvironment

environment = PolygonEnvironment()
boundary_coordinates = [(-3573.063493809924, -3397.7041999887488), (1301.0459112892288, -252.2710863523747), (1301.15422849654, -252.28188515495947), (4770.1483895222245, -3628.3511913003213), (2834.943959525434, 3975.1684750915865), (-1867.1813387156046, 2849.7191787712245)]
list_of_holes = [[(2060.962499654814, 2402.856442923204), (2061.0991856380538, 2402.7975366689266), (2505.6489788642275, 1262.568360564638), (2505.4964894782643, 1262.374772157754), (67.8754446874187, 1594.3012258568667), (67.82916999672895, 1594.6696523014614)]]
start = (2436.2142928243047, 1440.6619196276174)
end = (2505.6489788642275, 1262.568360564638)
environment.store(boundary_coordinates, list_of_holes, validate=False)
environment.prepare()
print(environment.within_map(start))
print(environment.within_map(end))
print(environment.find_shortest_path(start, end))

**Comment by MrMinimal64** [comment]
Thanks. It is debatable whether the start point actually lies within our outside of the "map". It all comes down to numerical precision at the end.

Use this instead:
`path, distance = environment.find_shortest_path(start, end, verify=False)`
