### ISSUE TITLE
ccw can't resolve path but cw can

### ISSUE THREAD

**Issue by PonyPC** [MrMinimal64/extremitypathfinder#12]
```
from extremitypathfinder import PolygonEnvironment

environment = PolygonEnvironment()
boundary_coordinates = [(-2670.0220709984246, 2849.785328817447), (-534.0066345219713, 4408.091718018869), (2347.252358687458, 3455.8632661053057), (-290.58214669197565, 122.69563577652582), (2576.3601774807016, -1781.9414137932943), (-3616.182881567927, -2546.608038824627)]
list_of_holes = []
start = (-3616.182881567927, -2546.608038824627)
end = (-290.58214669197565, 4327.64226042047)
environment.store(boundary_coordinates, list_of_holes, validate=False)
environment.prepare()
print(environment.find_shortest_path(start, end))
```
return ([], None)
but reverse boundary_coordinates, can get ([(-3616.182881567927, -2546.608038824627), (-2670.0220709984246, 2849.785328817447), (-534.0066345219713, 4408.091718018869), (-290.58214669197565, 4327.64226042047)], 8379.112990147512)

**Comment by MrMinimal64** [comment]
Please note that the boundary polygon has to be given in counter clockwise vertex numbering.
Use `validate=True` to check if the input data satisfies all prerequisites:
`environment.store(boundary_coordinates, list_of_holes, validate=True)`

**Comment by PonyPC** [comment]
I mean that the example code has already been counter clockwise.
It seems find_visibiliy returns empty list?

**Comment by PonyPC** [comment]
Sorry, I post wrong example code. Please use this:
```
from extremitypathfinder import PolygonEnvironment

environment = PolygonEnvironment()
boundary_coordinates = [(-3616.182881567927, -2546.608038824627), (2576.3601774807016, -1781.9414137932943), (-290.58214669197565, 122.69563577652582), (2347.252358687458, 3455.8632661053057), (-534.0066345219713, 4408.091718018869), (-2670.0220709984246, 2849.785328817447)]
list_of_holes = []
start = (-3616.182881567927, -2546.608038824627)
end = (-290.58214669197565, 4327.64226042047)
environment.store(boundary_coordinates, list_of_holes, validate=True)
environment.prepare()
print(environment.find_shortest_path(start, end))
```
It seems that find_visible return empty list.

**Comment by MrMinimal64** [comment]
For me this correctly returns `([(-3616.182881567927, -2546.608038824627), (-290.58214669197565, 4327.64226042047)], 7636.421768372853)`.
Which result do you expect?

**Comment by PonyPC** [comment]
But on my computer, it returns ([], None)

**Comment by MrMinimal64** [comment]
please update to the latest version of `extremitypathfinder`, use python3.7+ and maybe also try this:

`    boundary_coordinates = list(reversed(boundary_coordinates))`

**Comment by PonyPC** [comment]
python3.8 extremitypathfinder1.3.0, 
[(-3616.182881567927, -2546.608038824627), (2576.3601774807016, -1781.9414137932943), (-290.58214669197565, 122.69563577652582), (2347.252358687458, 3455.8632661053057), (-534.0066345219713, 4408.091718018869), (-2670.0220709984246, 2849.785328817447)]
already count clockwise, need it reversed again?

**Comment by MrMinimal64** [comment]
Not normally. I get regular results with this input.

**Comment by PonyPC** [comment]
So strange.
If I change end point from (-290.58214669197565, 4327.64226042047) to (-290.58214669197565, 4327.64226042046), it will return right path.
last value from 7 to 6
But find_shortest_path has been verified.

**Comment by PonyPC** [comment]
F**k numpy!
numpy==1.18.3 cause the problem.
I update numpy to 1.18.4, and be fixed.

**Comment by PonyPC** [comment]
Considering update requirements.txt to:
numpy>=1.16,!=1.18.3

**Comment by MrMinimal64** [comment]
Thanks for resolving this. is it only caused by `numpy==1.18.3`?
or should i rather set the requirements to `numpy>=1.18.4`

**Comment by PonyPC** [comment]
It's so strange again....
I uninstalled 1.18.4 and reinstall 1.18.1, 1.18.2, 1.18.3, it can still resolve path.
I really don't know why...........

**Comment by MrMinimal64** [comment]
ok, then for now i will leave the requirements as is. let me know if you find the cause of the complications. thanks

**Comment by PonyPC** [comment]
sorry for disturbing you.

**Comment by PonyPC** [comment]
Please....see this example, this is count clockwise already, if I remove a point such as (25.143824159896702, 50.75304334650772) it will pass validation:
```
from extremitypathfinder import PolygonEnvironment

environment = PolygonEnvironment()
boundary_coordinates = [(-2149.4036256395066, 2001.7590183818127), (-3431.0233936218774, 2410.5647452618605), (-4017.2943008798484, 1361.978351815837), (-1054.546974197546, 997.7866275442141), (-3181.1501133246757, -1967.5897135182254), (25.055804799501843, 50.756640615771744), (25.143824159896702, 50.75304334650772), (3389.8934865553656, -2472.9651791492142), (1882.5620718508735, 1507.675315397706), (3879.9702870888277, 4442.818958344931), (437.15881723989327, 2851.364918310943), (-2055.8189838443313, 4870.213713763695), (-2864.980706317556, 3422.9715569745244)]
list_of_holes = []
start = (-2149.4036256395066, 2001.7590183818127)
end = (437.15881723989327, 2851.364918310943)
environment.store(boundary_coordinates, list_of_holes, validate=True)
environment.prepare()
print(environment.find_shortest_path(start, end))
```
assert not has_clockwise_numbering(boundary_coords)

**Comment by PonyPC** [comment]
Okay, the problem fixed, thanks

**Comment by PonyPC** [comment]
😂😂😂😂 Sorry again....
```
from extremitypathfinder import PolygonEnvironment
environment = PolygonEnvironment()
boundary_coordinates = [(4196.035531444209, 1524.5174141906843), (120.45899596761083, 1964.5309552310625), (-1560.1327143180315, 3953.1950461671404), (-1845.7183461510908, 2184.3530258772616), (-4008.99249567332, 2308.524464730015), (-2077.147281929666, 104.95988170636463), (-4397.1723772192245, -1684.1387542764294), (-3542.469485595629, -2760.93575183657), (-3542.443309415404, -2760.9398379707277)]
list_of_holes = []
start = (4196.035531444209, 1524.5174141906843)
end = (-2077.147281929666, 104.95988170636463)
environment.store(boundary_coordinates, list_of_holes, validate=True)
environment.prepare()
print(environment.find_shortest_path(start, end, verify=True))
```
assert not np.allclose(p1, p2)

**Comment by PonyPC** [comment]
if I change 
```
assert not np.allclose(p1, p2)
```
to 
```
assert not np.allclose(p1, p2, rtol=1e-09)
```
it return ([], None) again.

**Comment by MrMinimal64** [comment]
what are `p1` and `p2`? and what do you want to achieve?
please open up new issue for every case to avoid confusion.
