### ISSUE TITLE
assert error while polygon two points are extremely close

### ISSUE THREAD

**Issue by PonyPC** [MrMinimal64/extremitypathfinder#13]
Example code
```
from extremitypathfinder import PolygonEnvironment
environment = PolygonEnvironment()
boundary_coordinates = [(4196.035531444209, 1524.5174141906843), (120.45899596761083, 1964.5309552310625), (-1560.1327143180315, 3953.1950461671404), (-1845.7183461510908, 2184.3530258772616), (-4008.99249567332, 2308.524464730015), (-2077.147281929666, 104.95988170636463), (-4397.1723772192245, -1684.1387542764294), (-3542.469485595629, -2760.93575183657), (-3542.443309415404, -2760.9398379707277)]
list_of_holes = []
start = (4196.035531444209, 1524.5174141906843)
end = (-2077.147281929666, 104.95988170636463)
environment.store(boundary_coordinates, list_of_holes, validate=True)
environment.prepare()
print(environment.find_shortest_path(start, end, verify=True))
```

**Comment by PonyPC** [comment]
It raise assert error:
assert not np.allclose(p1, p2)
in helper_fcts.py

**Comment by MrMinimal64** [comment]
Please note that two consequent polygon vertices are not allowed to be similar (cf. [Documentation ](https://extremitypathfinder.readthedocs.io/en/latest/4_api.html#extremitypathfinder.PolygonEnvironment.store)). 
This is to avoid numerical instabilities. Adjust the allowed similarity or set `validate=False` at the risk of obtaining incorrect results.

**Comment by MrMinimal64** [comment]
May I ask what you are using this package for? I am curious about the use cases the users have, so I can improve the package in the future. Thanks

**Comment by PonyPC** [comment]
If I set validate=False, it will return [], None.
I'm using this package for multi robots automaticly delivering.

**Comment by MrMinimal64** [comment]
This is probably due to numerical instability. Simply delete all similar vertices before passing it as input.

**Comment by PonyPC** [comment]
Okay, thanks dude.
