### ISSUE TITLE
Allow for overlapping polygons

### ISSUE THREAD

**Issue by georghess** [MrMinimal64/extremitypathfinder#20]
Currently, overlapping polygons cannot be handled. In my experience, they often yield paths that go through polygons that overlap, rather than around. 

At https://github.com/georghess/extremitypathfinder/tree/overlapping-polygons a potential fix addresses this when preparing the visibility graph. Basically, extremities that are within a polygon or outside the boundary should not be considered visible:

```
while len(extremities_to_check) > 0:
    # extremities are always visible to each other (bi-directional relation -> undirected graph)
    #  -> do not check extremities which have been checked already
    #  (would only give the same result when algorithms are correct)
    # the extremity itself must not be checked when looking for visible neighbours
    query_extremity: PolygonVertex = extremities_to_check.pop()
    # only extremities that are within the map are visible to other extremities
    if not self.within_map(query_extremity.coordinates):
        continue
```

Further, neighbours of `query_extremity` should not automatically be considered visible, since overlapping polygons might obstruct the view, e.g. just remove

```
try:
    candidate_extremities.remove(n1)
    visible_vertices.add((n1, n1.get_distance_to_origin()))
except KeyError:
    pass
try:
    candidate_extremities.remove(n2)
    visible_vertices.add((n2, n2.get_distance_to_origin()))
except KeyError:
    pass
```

Adjusted code passes all tests and produces feasible paths for overlapping polygons as far as I've seen.

**Comment by MrMinimal64** [comment]
Thanks for the input, could you please open up a pull request with the changes you have made?
It would also be very helpful if you added some new test cases for overlapping polygons.
Any contributions are welcome!
