### ISSUE TITLE
add comand line interface

### ISSUE THREAD

**Issue by MrMinimal64** [MrMinimal64/extremitypathfinder#22]
e.g. read polygons and holes from .json files?

**Comment by idoria75** [comment]
Is anyone implementing this? I can give it a try if still needed

**Comment by MrMinimal64** [comment]
Hello Ivan, than you for your interest. Yes please, your contribution would be very welcome!
Do not hesitate to ask any questions.

**Comment by idoria75** [comment]
Hello @MrMinimal64, I took a look at the docs and also now have the environment setup. The goal is to have a custom command (e.g. `$ findshortestpath <boundaries_and_holes.json>`), right? Are there other commands that would be interesting to offer as well?

**Comment by MrMinimal64** [comment]
Yes, exactly. It would be nice if a user could use the package even from a "non-python" context. So supporting the basic functionality of the package (https://extremitypathfinder.readthedocs.io/en/latest/1_usage.html) should be enough for the start. 
Something like `python extremitypathfinder.py <boundaries_and_holes.json> <start> <goal>` would be cool.
You can refer to this example: https://timezonefinder.readthedocs.io/en/latest/1_usage.html#calling-timezonefinder-from-the-command-line

**Comment by idoria75** [comment]
Hello Jannik. I am having a hard time to setup the virtual environment to properly run either of your packages (extremitypathfinder and timezonefinder).

I have a new virtual environment with Python 3.7 as listed on the requirements:

```bash
(pathfinder) $ python --version
Python 3.7.9

(pathfinder) $ which python
/home/ivan/.virtualenvs/pathfinder/bin/python

(pathfinder) $ pip list
Package             Version
------------------- -------
extremitypathfinder 2.1.0
numpy               1.19.5
pip                 20.3.1
setuptools          51.0.0
timezonefinder      5.0.0
wheel               0.36.1
```

When I try to run the example from the timezonefinder, I get the following:
```bash
(pathfinder) $ python timezonefinder.py 40.5 11.7
```
```python
Traceback (most recent call last):
  File "timezonefinder.py", line 13, in <module>
    from timezonefinder.global_settings import (
  File "/home/ivan/dev/open-source/timezone/timezonefinder/timezonefinder/timezonefinder.py", line 13, in <module>
    from timezonefinder.global_settings import (
ModuleNotFoundError: No module named 'timezonefinder.global_settings'; 'timezonefinder' is not a package
```
This happens when I call the timezonefinder.py from within the repo's clone folder:
```bash
(pathfinder) $ pwd
<local_path_to_repo_clone>/timezonefinder/timezonefinder
```
So the file python script is found, and as seen on the `pip list` output, the package is also installed.

I don't have much experience with virtual environments, but I have looked at tutorials in order to have everything setup properly with the right versions. I still can't seem to find what I'm doing wrong. Do you have any clue on what I could be missing?

**Comment by MrMinimal64** [comment]
It is not your fault but rather a bug in the package. It has to do with how imports work in python. I will fix it and upload the new version.
This documentation describes how to setup a command line interface instead: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html

**Comment by MrMinimal64** [comment]
Please check out the latest version 5.1.0 of `timezonefinder`. If you have installed this version, you can directly call `timezonefinder 40.5 11.7`

**Comment by idoria75** [comment]
This new version worked properly. I have started developing on this [branch](https://github.com/idoria75/extremitypathfinder/tree/cli_interface).
After installing the package, I can run the command `extremitypathfinder` and print the contents from a  json file back to the terminal. 

I will keep my branch updated with my latest developments, and hopefully I can have some more time soon to finish implementing this.

**Comment by MrMinimal64** [comment]
Thank you for your Contribution!
I made some additional edits and uploaded a new version of the package including your CLI.
